### ISSUE TITLE
Think of better name than "Survival Board Game"

### ISSUE THREAD

**Issue by leunarie** [leunarie/Survival-Board-Game#2]

**Comment by samstewart21** [comment]
**List of Possible Names:**

Get Off The Island
Get Off My Island
Tropical SurviveLand
SurviveLand
Survive An Island
Survival Island
The Island

**Comment by samstewart21** [comment]
So far, Get Off My Island has the most votes. We will decide on the final name at the next meeting.

![poll-results](https://user-images.githubusercontent.com/33586714/92548242-83129900-f224-11ea-9a54-f02a44b678d8.png)

**Comment by samstewart21** [comment]
**Updated List of Game Ideas**
stranded on coconut island
stranded on castaway island ((any noun in front of island)
get off my island

**Comment by samstewart21** [comment]
We decided on using Get Off My Island as the final name of the game.
